--CREATING A DATABASE FROM CURRENT DATE AND TIME
CREATE TABLE test(
	my_date DATE,
    my_time TIME,
    my_datetime DATETIME
);

--GETTING THE CURRENT DATE AND TIME
INSERT INTO test
VALUES(CURRENT_DATE(), CURRENT_TIME(), NOW());

SELECT * FROM test;

--YOU CAN USE +/1 TO ADJUST DATE/TIME
INSERT INTO test
VALUES(CURRENT_DATE() +1, NULL, NULL);

SELECT * FROM test;

